version: '3.8'

services:
  discord-crypto-bot:
    build: .
    container_name: discord-crypto-screening-tool
    env_file: .env
    volumes:
      - ./pairs_cache.json:/app/pairs_cache.json
    restart: unless-stopped
    dns:
      - 127.0.0.1